name: treatment-efficacy-env
dependencies:
  - graphviz>=0.8.1
  - numpy>=1.12.1
  - pandas>=0.23.3
  - matplotlib>=2.0.2
  - scikit-learn>=0.18.1
  - scipy>=0.19.0
  - seaborn>=0.7.1
  - statsmodels>=0.8.0
  - Cython>=0.25.2
  - ipykernel>=4.8.2